import type { Telemetry } from './types'
export const initialTelemetry: Telemetry = {
  phone_state: 'waiting',
  laptop: { available: false, width: null, height: null, age_ms: null },
  phone: { available: false, width: null, height: null, age_ms: null },
  calibration: {
    status: 'not_started',
    health: 'unavailable',
    message: 'Calibrate camera intrinsics first.',
    accepted_views: 0,
    rejected_views: 0,
    baseline_cm: null,
    median_reprojection_error_px: null,
    median_stereo_reprojection_error_px: null,
    median_pairing_error_ms: null,
    inlier_views: 0,
    outlier_views: 0,
  },
  intrinsics: {
    camera_id: '',
    status: 'not_started',
    message: 'Create a profile for each camera.',
    accepted_views: 0,
    rejected_views: 0,
    required_views: 25,
    reprojection_error_px: null,
  },
  hand_tracking: {
    status: 'unavailable',
    reason: 'calibration_required',
    timing_error_ms: null,
    confidence: 0,
    raw_points_m: null,
    filtered_points_m: null,
    reprojection_residuals_px: null,
    landmark_confidence: null,
    laptop_landmarks_normalized: null,
    phone_landmarks_normalized: null,
    secondary_raw_points_m: null,
    secondary_filtered_points_m: null,
    secondary_reprojection_residuals_px: null,
    secondary_landmark_confidence: null,
    laptop_hands_landmarks_normalized: [],
    phone_hands_landmarks_normalized: [],
  },
  interaction: {
    state: 'idle',
    gesture: null,
    gesture_confidence: 0,
    hold_progress: 0,
    hold_elapsed_ms: 0,
    hold_required_ms: 0,
    pinch: false,
    pinch_distance_m: null,
    secondary_pinch: false,
    secondary_pinch_distance_m: null,
    two_hand_pinch: false,
    two_hand_distance_m: null,
    cursor_m: null,
    object_position_m: [0, 0, 0.45],
    object_scale_m: 0.11,
    object_rotation_quat: [0, 0, 0, 1],
    model_id: 'car',
    wrist_twist_active: false,
    object_status: 'draft',
    laptop_object_corners_normalized: null,
    phone_object_corners_normalized: null,
    laptop_object_points_normalized: null,
    phone_object_points_normalized: null,
    laptop_hand_depth_relation: 'unknown',
    phone_hand_depth_relation: 'unknown',
    detector_reason: null,
    events: [],
  },
  processing: {
    status: 'latest_frame_wins',
    hand_inference_duration_ms: null,
    gesture_inference_duration_ms: null,
  },
}
